### ISSUE TITLE
scope is not accurate for reactions with a shared metabolite in reactants and products

### ISSUE THREAD

**Issue by cfrioux** [cfrioux/fluto#1]
The following case leads to a more permissive scope than expected:

```
---> S # S is a seed/nutrient
S + I --> I + T
```

Because of `N!=M` in the scope rules, a reactant of a reaction does not have to be producible if it is also a product of the (same) reaction. It is more permissive than the strict Ebenhöh-Hendorf scope definition.

In the example above, the recycling of I would be allowed by default and all four compounds would be in the scope of S. The Ebenhöh-Hendorf scope definition expects only `S`to be producible.

**Comment by sthiele** [comment]
I think the change is not so bad it is kind of in between Handorf and Sagot ... maybe worth further investigating? ... maybe make it an option?

I have also rewritten this in my branch but I also did some other changes:

https://github.com/sthiele/fluto/blob/29db39ff070a8f95ec4f0603e856a7c78814e51d/flutopy/encodings/top-gf-encoding.lp#L25-L29

**Comment by cfrioux** [comment]
I agree that it can be interesting to keep this definition in mind for a future option as an in-between EH and SA semantics. In the end we will merge your developments so I suggest to remove temporarily this behaviour on master and make the new incoming version of fluto more flexible on the semantics?

**Comment by sthiele** [comment]
Yup
